# This project is written in PHP
language: php

# Test on the following versions:
php:
    - 5.3.3
    - 5.3
    - 5.4

script:
    - php composer.phar self-update
    - php composer.phar install
    - phpunit -c tests/phpunit.xml
    
